### ISSUE TITLE
Change group name

### ISSUE THREAD

**Issue by adamw** [softwaremill/reactive-kafka#27]
Currently it's a generic `com.softwaremill`, probably would be better to have a kafka-specific one?

**Comment by kciesielski** [comment]
+1
I was thinking about the same recently, because I'm working on manual commit to Zookeeper which apparently needs some additional dependencies (like `curator-framework` or `curator-recipes`). This made me think about making ZK commit support an optional module (since using ZK for commits is already deprecated in Kafka) and then I realized that the root groupId may be too general :)
